### ISSUE TITLE
Menu location is not registered

### ISSUE THREAD

**Issue by rain2o** [Myzwer/foothillschurch#23]
https://github.com/Myzwer/foothillschurch/blob/d75494784caf988edbcdb95afebe7becdca009e7/header.php#L95

I'm a little confused. Unless I'm missing something, this is using a menu location that isn't registered. I couldn't get it to work on my local without changing this to `main-navigation`

**Comment by Myzwer** [comment]
Yeah this shouldn't be working. Must have been a caching thing? Not sure. Either way, swapped it out. That was what it was called in my template, but I updated it since this site has 2 navbars.
