### ISSUE TITLE
Invalid HTML: Button inside anchor tag

### ISSUE THREAD

**Issue by rain2o** [Myzwer/foothillschurch#26]
https://github.com/Myzwer/foothillschurch/blob/d75494784caf988edbcdb95afebe7becdca009e7/frontpage.php#L137-L138

This is invalid HTML. An `<a>` tag should be used when a user is directed to a new page. Semantically, a `<button>` should be used when an effect is caused by the click (like a modal or something). If you want to style an anchor tag like a button that's fine, but it should be all styles doing this.

Side note: this specific link doesn't have a hover effect. For accessibility (and generally better UX) anything clickable should indicate it is by changing its appearance in some way on hover.

**Comment by rain2o** [comment]
I'm seeing this trend in multiple places. I'm not going to comment on each one, but this applies anywhere this nesting happens.

**Comment by Myzwer** [comment]
After editing 18 files, this is done.
