### ISSUE TITLE
Pagination big numbers are confusing

### ISSUE THREAD

**Issue by rain2o** [Myzwer/foothillschurch#32]
https://github.com/Myzwer/foothillschurch/blob/d75494784caf988edbcdb95afebe7becdca009e7/archive-message.php#L60-L62

What's happening here? I don't even understand what's being accomplished.

Besides the confusion of why this exists, a couple of notes.

You define `$big` as `999999999`, but then you don't use `$big` anywhere. But you do use `999999999` a couple of places. Maybe those are meant to use `$big` instead?

**Comment by rain2o** [comment]
Same here, should use `$big` since you defined it
https://github.com/Myzwer/foothillschurch/blob/effc5bbf81497ae99f0561ab7849412fe9272bfd/archive-transcripts.php#L60-L62

**Comment by Myzwer** [comment]
Completely refactored pagination before I even got here, so this is taken care of. I believe this was created using a tutorial a while ago, so I don't know what the purpose of $big was. Either way, it's gone now.
