### ISSUE TITLE
Content is off-centered

### ISSUE THREAD

**Issue by rain2o** [Myzwer/foothillschurch#35]
https://github.com/Myzwer/foothillschurch/blob/effc5bbf81497ae99f0561ab7849412fe9272bfd/contact.php#L21-L29

The content of this template looks off-centered. Looks like it's because the `prose` class adds a `max-width` so the content doesn't fill the grid fully

**Comment by rain2o** [comment]
This also seems to be happening in `privacy-policy.php`

**Comment by rain2o** [comment]
Also in `components/blocks/blog.php`

**Comment by rain2o** [comment]
And in `components/blocks/faq-long.php`

**Comment by Myzwer** [comment]
This is actually an intentional choice. Makes content easier to read since your eyes don't have to track as far across the screen. We called it "blog style" when designing the site.

**Comment by rain2o** [comment]
Interesting choice. It definitely looks unintentional. Maybe the wrapper should be offset more so that the container is centered (i.e. you're using 8 of 12 cols, so offset by 4 on each side as opposed to 2 and 6). The content can remain the decided width but it will be aligned in a way that doesn't feel as broken.
