### ISSUE TITLE
Just a note about arrays

### ISSUE THREAD

**Issue by rain2o** [Myzwer/foothillschurch#39]
https://github.com/Myzwer/foothillschurch/blob/effc5bbf81497ae99f0561ab7849412fe9272bfd/events.php#L39-L40

This isn't an issue; I just wanted to let you know. If you get tired of always writing out `array()`, you can use `[]`. In the example above it would be `'post_type'   => ['event'],`. An empty array would be like `$arr = [];` and with multiple items would be `$arr = ['item 1', 'item 2']`. Same as `array()` pretty much in every way except not needing to use the word array.

Just a small ergonomic improvement when writing code.

**Comment by Myzwer** [comment]
Good to know. 👍
