### ISSUE TITLE
BG image directly linked to Unsplash

### ISSUE THREAD

**Issue by rain2o** [Myzwer/foothillschurch#45]
https://github.com/Myzwer/foothillschurch/blob/effc5bbf81497ae99f0561ab7849412fe9272bfd/home.php#L19

Are you meaning to use this image directly from unsplash? Might be better to download and compress it and use it like your other bg images. Or from wp uploads if you want it in the CMS.

**Comment by Myzwer** [comment]
Nope lol, this ships stock with the template so something displays when I look at the page, but since this site doesn't have a blog I never actually updated this file.
