### ISSUE TITLE
FAQ cleanup

### ISSUE THREAD

**Issue by rain2o** [Myzwer/foothillschurch#61]
https://github.com/Myzwer/foothillschurch/blob/effc5bbf81497ae99f0561ab7849412fe9272bfd/components/layouts/faq.php#L15-L18

You could put this if condition outside of all markup in this component, so nothing is rendered if it's false.

https://github.com/Myzwer/foothillschurch/blob/effc5bbf81497ae99f0561ab7849412fe9272bfd/components/layouts/faq.php#L50-L51

Also this else isn't needed, it doesn't do anything.

**Comment by Myzwer** [comment]
Ended up reworking this so I didn't need this file.
